allowBuilds:
  '@whiskeysockets/baileys': true
  better-sqlite3: true
  esbuild: false
  protobufjs: true
  sharp: true

onlyBuiltDependencies:
  - better-sqlite3
  - esbuild
  - protobufjs
  - sharp

pnpm:
  minimumReleaseAge: 4320
  overrides:
    '@whiskeysockets/baileys>libsignal': 'libsignal@6.0.0'
